# ★ NAMESPACE — logische Trennwand im Cluster
#
# Alles was zu diesem Projekt gehört läuft im Namespace "todoapp-staging".
# Damit sind Ressourcen anderer Projekte sauber getrennt.
# → kubectl get pods -n todoapp-staging  (nur unsere Pods sehen)

apiVersion: v1
kind: Namespace
metadata:
  name: todoapp-staging       # ★ dieser Name taucht in JEDER anderen Datei unter "namespace:" auf
  labels:
    app.kubernetes.io/managed-by: kubectl
    environment: staging
